"""calibrate_factor_weights.py — evidence-driven factor weights from measured IC.

Reads public/data/factor_ic.json (written by backtest_lite.py) and writes
scripts/factor_weights.json consumed by score_factors.py.

Scheme:
  - revisions + theme have no point-in-time history (sidecars are recent), so
    they get FIXED weights of 0.075 each — small, honest, non-zero.
  - the remaining 0.85 budget is split across the measurable factors
    (value / quality / momentum / lowvol) proportionally to max(0, mean_ic),
    with a 0.05 floor for any factor whose mean IC is positive.
  - if every measurable IC is <= 0 (shouldn't happen), fall back to equal.

The file keeps a dated history of every calibration so weight drift is
auditable. Survivorship caveat from the backtest applies to the ICs too —
they rank factors against each other; they don't promise absolute returns.

Usage: python scripts/calibrate_factor_weights.py
"""

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except Exception:
    pass

ROOT = Path(__file__).resolve().parents[1]
FACTOR_IC_JSON = ROOT / "public" / "data" / "factor_ic.json"
WEIGHTS_JSON = Path(__file__).resolve().with_name("factor_weights.json")

FIXED = {"revisions": 0.075, "theme": 0.075}
MEASURABLE = ["value", "quality", "momentum", "lowvol"]
MEASURABLE_BUDGET = 1.0 - sum(FIXED.values())
FLOOR = 0.05


def main():
    if not FACTOR_IC_JSON.exists():
        print(f"FATAL: {FACTOR_IC_JSON} missing — run backtest_lite.py first.")
        sys.exit(1)
    ic_data = json.loads(FACTOR_IC_JSON.read_text(encoding="utf-8"))
    factors = ic_data.get("factors", {})

    mean_ics = {f: (factors.get(f) or {}).get("mean_ic") for f in MEASURABLE}
    raw = {f: max(0.0, ic) for f, ic in mean_ics.items() if ic is not None}
    if not raw or sum(raw.values()) == 0:
        weights = {f: MEASURABLE_BUDGET / len(MEASURABLE) for f in MEASURABLE}
    else:
        total = sum(raw.values())
        weights = {f: MEASURABLE_BUDGET * raw.get(f, 0.0) / total for f in MEASURABLE}
        # Floor any positive-IC factor at FLOOR, renormalize the rest
        floored = {f for f, ic in mean_ics.items()
                   if ic is not None and ic > 0 and weights.get(f, 0) < FLOOR}
        if floored:
            for f in floored:
                weights[f] = FLOOR
            rest = [f for f in weights if f not in floored]
            rest_budget = MEASURABLE_BUDGET - FLOOR * len(floored)
            rest_total = sum(weights[f] for f in rest)
            if rest_total > 0:
                for f in rest:
                    weights[f] = rest_budget * weights[f] / rest_total

    weights.update(FIXED)
    weights = {f: round(w, 4) for f, w in weights.items()}
    # Absorb rounding drift into the largest weight so they sum to exactly 1
    drift = round(1.0 - sum(weights.values()), 4)
    biggest = max(weights, key=weights.get)
    weights[biggest] = round(weights[biggest] + drift, 4)

    prior = {}
    if WEIGHTS_JSON.exists():
        try:
            prior = json.loads(WEIGHTS_JSON.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            prior = {}
    history = prior.get("history", [])
    if prior.get("current"):
        history.append({"replaced_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
                        **prior["current"]})

    payload = {
        "current": {
            "calibrated_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
            "weights": weights,
            "mean_ics_used": mean_ics,
            "ic_quarters": {f: (factors.get(f) or {}).get("quarters") for f in MEASURABLE},
        },
        "history": history[-12:],  # keep last 12 calibrations
        "_note": ("Generated by calibrate_factor_weights.py. revisions/theme fixed at "
                  "0.075 (no point-in-time IC evidence); rest IC-proportional with 0.05 "
                  "floor. Edit by re-running the calibration, not by hand."),
    }
    WEIGHTS_JSON.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"Weights: {weights} (sum={sum(weights.values()):.4f})")
    print(f"Written: {WEIGHTS_JSON.name}")


if __name__ == "__main__":
    main()
